### PR TITLE
Start migration to JuMP that has complementarity support

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by odow** [comment]
Oh. There's a lot you'll need to change here.

The use of `@eval` and interpolating into the macros is a very bad code smell.

https://github.com/anthofflab/MPSGE.jl/blob/6597ef47c7f7213807fb888a7b3e1645be5c71de/src/build/build_variables.jl#L25

Do instead something like:
```julia
function variable_dense_axis_array(model, sector)
    dim = length.(sector.indices)
    x = @variable(model, [1:prod(dim)], lower_bound = 0)
    for (i, index) in enumerate(Iterators.product(sector.indices...))
        set_name(x[i], "$(sector.name)[$index]")
    end
    return JuMP.Containers.DenseAxisArray(reshape(x, dim), sector.indices...)
end
```

There's also a bunch of expression building like this which uses `eval`:
https://github.com/anthofflab/MPSGE.jl/blob/6597ef47c7f7213807fb888a7b3e1645be5c71de/src/build/build_implicitconstraints.jl#L13-L52

I would hope the first part of that just becomes:
```julia
    if contains_our_param(pf.elasticity)
        ρ = (pf.elasticity - 1) / pf.elasticity
        demand_over_quantity = [jm[get_comp_demand_name(i)] / i.quantity for i in pf.inputs]
        return @expression(
            jm,
            ifelse(
                pf.elasticity == 0.0,
                min(demand_over_quantity...),
                ifelse(
                    pf.elasticity == 1.0,
                    prod(demand_over_quantity[i]^Θ(pf, i) for i in pf.inputs),
                    sum(Θ(pf,i) * demand_over_quantity[i]^ρ for i in pf.inputs)^(1 / ρ),
                )
            ),
        )
```

In general, you should never need to use `eval` or `@eval`.

**Comment by odow** [comment]
I removed the use of `@eval` here: https://github.com/anthofflab/MPSGE.jl/pull/124.

But the bigger change is essentially a rewrite of the entire package. You need to swap from using Julia `Expr` to JuMP's `NonlinearExpr`.

The downside is that this is a lot of work. Sorry for that.

The upside is that you should be able to remove Complementarity.jl, and once rewritten, everything should be a lot simpler and more maintainable.

Something like:
```Julia
function build_incomebalance!(m, jm)
    # Add income balance constraints
    for c in m._demands
        ex6a = :(
            JuMP.@NLexpression(
                $jm,
                +($((:($(en.quantity) * 
                $(en.commodity)) for en in c.endowments)...)) 
                +  $(get_tax_revenue_for_consumer(jm, m, c.consumer)) 
                -
                $(c.consumer)
            )
        )

        ex6b = eval(swap_our_Ref_with_jump_var(jm, ex6a))
        Complementarity.add_complementarity(jm, get_jump_variable_for_consumer(jm, c.consumer), ex6b, string("F_", get_name(c.consumer, true)))
        push!(m._nlexpressions, ex6b)
    end
end
```
should become
```Julia
function build_incomebalance!(m, jm)
    JuMP.@constraint(
        jm, 
        c_income_balance[c in m._demands],
        sum(en.quantity * en.commodity for en in c.endowments) + 
            get_tax_reveue_for_consumer(jm, m, c.consumer) - c.consumer
        ⟂ get_jump_variable_for_consumer(jm, c.consumer),
    )
end
```

**Comment by davidanthoff** [comment]
Thanks! Yeah, the `eval`s had been on our list to remove for a while, I think they were there originally in one case for some good reason that I forgot, and then we just kept the pattern everywhere...

I did manage to get one of our tests to pass yesterday without a package rewrite ;) Essentially my strategy was to just transform an `Expr` tree into a `NonlinearExpr` structure, which was very simple, and then the changes required were actually pretty minimal. I think that is probably the best strategy for now, as we will always have some user-constructions that reach us in the form of `Expr`, so we might as well stick with that, I think, and then just do on transform before we actually add things to the JuMP model.

And yeah, I should say we are _very_ excited to see this all move into JuMP! If that causes some extra pain for us now that is certainly well worth the price.

**Comment by odow** [comment]
Ah that's a nice solution for the near-term.

**Comment by davidanthoff** [comment]
I think this is all done now. Tests are just failing because this needs `JuMP#master` and CI is not picking that one up. But as soon as the new JuMP is tagged, we can merge this.

**Comment by odow** [comment]
🎆

**Pull request merged**
